version: "2"

services:
  php-apache:
    build:
      context: .
      dockerfile: .docker/php-apache/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    networks:
      - laravel

  redis:
    image: redis:4.0
    container_name: app_redis
    ports:
      - "6382:6379"
    networks:
      - laravel      

networks:
  laravel:
